<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pemeliharaan_model extends CI_Model
{

    public $table = 'pemeliharaan';
    public $id = 'Id_Pemeliharaan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('Id_Pemeliharaan', $q);
	$this->db->or_like('Id_Keypoint', $q);
	$this->db->or_like('Id_Baterai', $q);
	$this->db->or_like('Id_Gatway', $q);
	$this->db->or_like('Id_Gembok', $q);
	$this->db->or_like('Id_Lokasi', $q);
	$this->db->or_like('Id', $q);
	$this->db->or_like('Id_SIM', $q);
	$this->db->or_like('Id_Status_Switch_Gear', $q);
	$this->db->or_like('Status_Akhir', $q);
	$this->db->or_like('Kesiapan_Peralatan', $q);
    $this->db->or_like('Titik_Terpelihara', $q);
    $this->db->or_like('TGL_PERGANTIAN_BATERAI', $q);
	$this->db->or_like('TGL_HAR_TERAKHIR', $q);
	$this->db->or_like('Keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('Id_Pemeliharaan', $q);
	$this->db->or_like('Id_Keypoint', $q);
	$this->db->or_like('Id_Baterai', $q);
	$this->db->or_like('Id_Gatway', $q);
	$this->db->or_like('Id_Gembok', $q);
	$this->db->or_like('Id_Lokasi', $q);
	$this->db->or_like('Id', $q);
	$this->db->or_like('Id_SIM', $q);
	$this->db->or_like('Id_Status_Switch_Gear', $q);
	$this->db->or_like('Status_Akhir', $q);
	$this->db->or_like('Kesiapan_Peralatan', $q);
    $this->db->or_like('Titik_Terpelihara', $q);
    $this->db->or_like('TGL_PERGANTIAN_BATERAI', $q);
	$this->db->or_like('TGL_HAR_TERAKHIR', $q);
	$this->db->or_like('Keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    
    function get_limit_data2($q = NULL) {
        return $this->db->query("SELECT pml.*,
            lk.Area, lk.Rayon, lk.Gardu_Induk, 
            sg.Penyulang1, sg.Penyulang2, sg.Status_Switch_Gear,
            kp.Nama_Keypoint_Dilokasi, kp.Nama_Keypoint_Discada,
            md.Id_Modem, gt.Nama_Gatway, gt.Ip_Gatway, kp.GPS,
            kp.Alamat_Keypoint, kp.Jenis_Keypoint, md.Type_Modem,
            md.No_IMEI_SN, md.Ip_Modem,
            kp.Merk_RTU, kp.No_Seri_RTU,
            sc.Provider, sc.IP_SIM, sc.No_SIM, sc.No_ICCID, 
            bt.Merk, bt.Kapasitas, bt.Jumlah, 
            gb.Gembok_Panel
        
        FROM pemeliharaan pml
        LEFT JOIN tb_keypoint kp ON pml.Id_Keypoint=kp.Id_Keypoint
        LEFT JOIN baterai bt ON pml.Id_Baterai=bt.Id_Baterai
        LEFT JOIN gatway gt ON pml.Id_Gatway=gt.Id_Gatway
        LEFT JOIN switch_gear sg ON pml.Id_Status_Switch_Gear=sg.Id_Status_Switch_Gear
        LEFT JOIN gembok gb ON pml.Id_Gembok=gb.Id_Gembok
        LEFT JOIN lokasi lk ON pml.Id_Lokasi=lk.Id_Lokasi
        LEFT JOIN sim_card sc ON pml.Id_SIM=sc.Id_SIM
        LEFT JOIN modem md ON pml.Id=md.Id
        WHERE lk.Area LIKE '%".$q."%' or kp.Nama_Keypoint_Dilokasi LIKE '%".$q ."%';");
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pemeliharaan_model.php */
/* Location: ./application/models/Pemeliharaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-30 17:30:38 */
/* http://harviacode.com */